### ISSUE TITLE
Some improvements for migration from OptaPlanner to Timefold

### ISSUE THREAD

**Issue by johanjanssen** [TimefoldAI/timefold-solver#27]
Thanks for Timefold and awesome that you provide OpenRewrite recipes for the migration!

I tried it on my (former) OptaPlanner example:
https://github.com/johanjanssen/JavaHiddenGems/tree/main/Examples/timefold

I used:
```
mvn org.openrewrite.maven:rewrite-maven-plugin:4.45.3:run -Drewrite.recipeArtifactCoordinates=ai.timefold.so
lver:timefold-solver-migration:0.8.38 -Drewrite.activeRecipes=ai.timefold.solver.migration.ToLatest
```

That gave the following problem:
`Non-resolvable import POM: ai.timefold.solver:timefold-solver-bom:pom:8.35.0.Final was not found in https://github.com/johanjanssen/JavaHiddenGems during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of repo has elapsed or updates are forced`

The version property was renamed, but the version wasn't changed, so I had to manually change the following line:
`<version.ai.timefold.solver>8.35.0.Final</version.ai.timefold.solver>
`
to
`<version.ai.timefold.solver>0.9.38</version.ai.timefold.solver>
`
That resolved the issue.

So not really a big deal, but maybe something that can be improved to make the migration even easier for other developers :).

Another idea might be to change Class and package names containing OptaPlanner as well, now I manually renamed some :).

The exact changes can be found in my commit:
https://github.com/johanjanssen/JavaHiddenGems/commit/bf6f02253740bc6b2cf12da5028eaa0e59eeb1b8

**Comment by ge0ffrey** [comment]
Thanks for the feedback Johan :) Very useful!

The version property changing is a known issue, fixed upstream - https://github.com/TimefoldAI/timefold-solver/issues/9
Once a new rewrite release goes out, it should be fixed.

**Comment by ge0ffrey** [comment]
1) Version property rename
Fixed by upgrading the website to use rewrite maven plugin 4.46.0

2) change Class and package names containing OptaPlanner as well, now I manually renamed
I understand why this is a good request and thanks for asking it, but the risk that we mess something up is too big.
For OptaPlanner we known and understand the type/usage patterns deeply. In user's code, we don't.
Rejected.

That being said, you can automate this for your code with OpenRewrite yourself :)

Here's how we changed some classes and packages:
```
type: specs.openrewrite.org/v1beta/recipe
name: ai.timefold.solver.migration.FromOptaPlannerToTimefoldSolver
displayName: Migrate from OptaPlanner to Timefold
description: 'Replaces your method/field calls, GAVs, etc. To replace deprecated methods too, use the recipe ToLatest'
recipeList:
  # Java files
  - org.openrewrite.java.ChangeType:
      oldFullyQualifiedTypeName: org.optaplanner.persistence.jackson.api.OptaPlannerJacksonModule
      newFullyQualifiedTypeName: ai.timefold.solver.jackson.api.TimefoldJacksonModule
      ignoreDefinition: true
  ...    
  - org.openrewrite.java.ChangePackage:
      oldPackageName: org.optaplanner
      newPackageName: ai.timefold.solver
      recursive: true
```
